public with sharing class RollupEngineConstants {

    public static final String SUM_FUNCTION = 'SUM';
    public static final String AVG_FUNCTION = 'AVG';
    public static final String MIN_FUNCTION = 'MIN';
    public static final String MAX_FUNCTION = 'MAX';
    public static final String COUNT_FUNCTION = 'COUNT';

    public static final String AGGREGATE_ALIAS = 'aggregateValue';

    public static final String ROLLUP_METADATA = 'Rollup_Config__mdt';

    public static final String PARENT_OBJECT_API = 'Parent_Object__c';
    public static final String PARENT_OBJECT_FIELD = 'Parent_Field__c';
    public static final String CHILD_OBJECT_API = 'Child_Object__c';
    public static final String CHILD_OBJECT_FIELD = 'Child_Field__c';
    public static final String RELATIONSHIP_FIELD = 'Relationship_Field__c';
    public static final String AGGREGATE_FUNCTION = 'Aggregate_Function__c';
    public static final String ACTIVE_FIELD = 'Active__c';
}
